<?php
if (!defined('ABSPATH')) exit;
/** Secure API surface reserved for EzLens Manager and mobile applications. */
class EzLens_Auth_API_V2 {
    private static $instance=null; private $ns='ezlens-app/v1';
    public static function get_instance(){return self::$instance?:self::$instance=new self();}
    private function __construct(){add_action('rest_api_init',[$this,'routes']);}
    private function rate($request,$bucket='api'){ $ip=sanitize_text_field($_SERVER['REMOTE_ADDR']??'0.0.0.0');$key='ezlens_rl_'.md5($bucket.'|'.$ip);$n=(int)get_transient($key);$limit=max(10,min(600,(int)EzLens_Auth_Settings::get('api_rate_limit')?:60));if($n>=$limit)return new WP_Error('rate_limited','تعداد درخواست‌ها بیش از حد مجاز است.',['status'=>429]);set_transient($key,$n+1,MINUTE_IN_SECONDS);return true; }
    private function bearer($request){$h=$request->get_header('authorization');if(preg_match('/Bearer\s+(.+)/i',(string)$h,$m))return trim($m[1]);return '';}
    private function user($request){if(EzLens_Auth_Settings::get('enable_api')!=='1')return new WP_Error('api_disabled','API غیرفعال است.',['status'=>403]);$ok=$this->rate($request,'api');if(is_wp_error($ok))return $ok;$token=$this->bearer($request);$uid=$token?EzLens_Auth_App_Auth::get_instance()->authenticate($token):0;if(!$uid)return new WP_Error('unauthorized','توکن معتبر نیست.',['status'=>401]);return $uid;}
    public function routes(){register_rest_route($this->ns,'/auth/request-otp',['methods'=>'POST','callback'=>[$this,'request_otp'],'permission_callback'=>'__return_true']);register_rest_route($this->ns,'/auth/verify-otp',['methods'=>'POST','callback'=>[$this,'verify_otp'],'permission_callback'=>'__return_true']);register_rest_route($this->ns,'/me',['methods'=>'GET','callback'=>[$this,'me'],'permission_callback'=>[$this,'permission']]);register_rest_route($this->ns,'/orders',['methods'=>'GET','callback'=>[$this,'orders'],'permission_callback'=>[$this,'permission']]);register_rest_route($this->ns,'/tickets',['methods'=>'GET','callback'=>[$this,'tickets'],'permission_callback'=>[$this,'permission']]);register_rest_route($this->ns,'/tickets',['methods'=>'POST','callback'=>[$this,'create_ticket'],'permission_callback'=>[$this,'permission']]);register_rest_route($this->ns,'/notifications',['methods'=>'GET','callback'=>[$this,'notifications'],'permission_callback'=>[$this,'permission']]);register_rest_route($this->ns,'/notifications/read',['methods'=>'POST','callback'=>[$this,'read_notification'],'permission_callback'=>[$this,'permission']]);register_rest_route($this->ns,'/auth/logout',['methods'=>'POST','callback'=>[$this,'logout'],'permission_callback'=>[$this,'permission']]);register_rest_route($this->ns,'/manager/customers',['methods'=>'GET','callback'=>[$this,'manager_customers'],'permission_callback'=>[$this,'admin_permission']]);register_rest_route($this->ns,'/manager/orders',['methods'=>'GET','callback'=>[$this,'manager_orders'],'permission_callback'=>[$this,'admin_permission']]);register_rest_route($this->ns,'/manager/campaigns',['methods'=>'GET','callback'=>[$this,'manager_campaigns'],'permission_callback'=>[$this,'admin_permission']]);register_rest_route($this->ns,'/manager/tickets',['methods'=>'GET','callback'=>[$this,'manager_tickets'],'permission_callback'=>[$this,'admin_permission']]);register_rest_route($this->ns,'/health',['methods'=>'GET','callback'=>[$this,'health'],'permission_callback'=>[$this,'admin_permission']]);}
    public function request_otp($r){if(EzLens_Auth_Settings::get('enable_api')!=='1'||EzLens_Auth_Settings::get('app_otp_enabled')!=='1')return new WP_Error('api_disabled','API/OTP اپ غیرفعال است.',['status'=>403]);$p=$r->get_json_params();$mobile=EzLens_Auth_Helper::normalize_mobile($p['mobile']??'');if(!preg_match('/^09\d{9}$/',$mobile))return new WP_Error('invalid_mobile','شماره موبایل نامعتبر است.',['status'=>400]);if(!EzLens_Auth_OTP::can_request($mobile,'app_login'))return new WP_Error('rate_limited','درخواست OTP بیش از حد مجاز است.',['status'=>429]);$code=EzLens_Auth_OTP::store($mobile,'app_login');if(!$code)return new WP_Error('otp_error','تولید کد ناموفق بود.',['status'=>500]);$result=EzLens_Auth_Messaging::get_instance()->send_otp($mobile,$code);if(empty($result['success']))return new WP_Error('sms_error',$result['message']??'ارسال پیامک ناموفق بود.',['status'=>502]);return ['success'=>true,'message'=>'کد تأیید ارسال شد.','latency_ms'=>$result['latency_ms']??null];}
    public function verify_otp($r){if(EzLens_Auth_Settings::get('enable_api')!=='1'||EzLens_Auth_Settings::get('app_otp_enabled')!=='1')return new WP_Error('api_disabled','API/OTP اپ غیرفعال است.',['status'=>403]);$p=$r->get_json_params();$mobile=EzLens_Auth_Helper::normalize_mobile($p['mobile']??'');$code=preg_replace('/\D/','',(string)($p['code']??''));$otp=EzLens_Auth_OTP::verify($mobile,$code,'app_login');if(empty($otp['success']))return new WP_Error('invalid_otp','کد تأیید نامعتبر یا منقضی است.',['status'=>401]);$user=EzLens_Auth_Helper::get_user_by_phone($mobile);if(!$user){$uid=wp_create_user($mobile,wp_generate_password(32),$mobile.'@ezlens.ir');if(is_wp_error($uid))return $uid;update_user_meta($uid,'billing_phone',$mobile);update_user_meta($uid,'user_phone',$mobile);$user=get_userdata($uid);} $token=EzLens_Auth_App_Auth::get_instance()->issue_token($user->ID,($p['device_name']??''),($p['platform']??''));EzLens_Auth_Audit::get_instance()->log('app.login',['user_id'=>$user->ID],'user',$user->ID);return ['success'=>true,'token'=>$token,'expires_in'=>max(1,min(365,(int)EzLens_Auth_Settings::get('app_token_days')?:30))*DAY_IN_SECONDS,'user'=>['id'=>$user->ID,'name'=>$user->display_name,'email'=>$user->user_email,'phone'=>$mobile]];}
    public function permission($r){$u=$this->user($r);return is_wp_error($u)?$u:true;}
    public function admin_permission($r){$u=$this->user($r);if(is_wp_error($u))return $u;return user_can($u,'manage_options')?true:new WP_Error('forbidden','دسترسی مجاز نیست.',['status'=>403]);}
    private function uid($r){$token=$this->bearer($r);return EzLens_Auth_App_Auth::get_instance()->authenticate($token);}
    public function me($r){$u=get_userdata($this->uid($r));if(!$u)return new WP_Error('not_found','کاربر یافت نشد.',['status'=>404]);return ['id'=>$u->ID,'name'=>$u->display_name,'email'=>$u->user_email,'phone'=>get_user_meta($u->ID,'billing_phone',true)?:get_user_meta($u->ID,'user_phone',true),'roles'=>$u->roles,'notifications_unread'=>EzLens_Auth_Notifications::get_instance()->unread_count($u->ID)];}
    public function orders($r){$uid=$this->uid($r);if(!function_exists('wc_get_orders'))return ['data'=>[],'woocommerce'=>false];$orders=wc_get_orders(['customer_id'=>$uid,'limit'=>20,'orderby'=>'date','order'=>'DESC']);$out=[];foreach($orders as $o)$out[]=['id'=>$o->get_id(),'status'=>$o->get_status(),'total'=>$o->get_total(),'currency'=>$o->get_currency(),'date'=>$o->get_date_created()?$o->get_date_created()->date('c'):null];return ['data'=>$out,'woocommerce'=>true];}
    public function tickets($r){$uid=$this->uid($r);return ['data'=>EzLens_Auth_Support::get_instance()->get_user_tickets($uid,20)];}
    public function create_ticket($r){$uid=$this->uid($r);$p=$r->get_json_params();$message=wp_kses_post($p['message']??'');if(!$message)return new WP_Error('invalid_message','پیام الزامی است.',['status'=>400]);$id=EzLens_Auth_Support::get_instance()->create_ticket($uid,$message);return ['success'=>(bool)$id,'ticket_id'=>(int)$id];}
    public function notifications($r){$uid=$this->uid($r);return ['data'=>EzLens_Auth_Notifications::get_instance()->list_for_user($uid,50),'unread'=>EzLens_Auth_Notifications::get_instance()->unread_count($uid)];}
    public function read_notification($r){$uid=$this->uid($r);$p=$r->get_json_params();return ['success'=>EzLens_Auth_Notifications::get_instance()->mark_read($uid,(int)($p['id']??0))];}

    public function logout($r){$token=$this->bearer($r);EzLens_Auth_App_Auth::get_instance()->revoke($token);return ['success'=>true];}
    public function manager_customers($r){$users=get_users(['number'=>50,'paged'=>max(1,(int)$r->get_param('page')),'fields'=>['ID','display_name','user_email']]);$out=[];foreach($users as $u)$out[]=['id'=>$u->ID,'name'=>$u->display_name,'email'=>$u->user_email,'phone'=>get_user_meta($u->ID,'billing_phone',true)?:get_user_meta($u->ID,'user_phone',true)];return ['data'=>$out];}
    public function manager_orders($r){if(!function_exists('wc_get_orders'))return ['data'=>[]];$orders=wc_get_orders(['limit'=>50,'paged'=>max(1,(int)$r->get_param('page')),'orderby'=>'date','order'=>'DESC']);$out=[];foreach($orders as $o)$out[]=['id'=>$o->get_id(),'customer_id'=>$o->get_customer_id(),'status'=>$o->get_status(),'total'=>$o->get_total(),'currency'=>$o->get_currency(),'date'=>$o->get_date_created()?$o->get_date_created()->date('c'):null];return ['data'=>$out];}
    public function manager_campaigns($r){$page=max(1,(int)$r->get_param('page'));$limit=max(1,min(50,(int)$r->get_param('per_page')?:20));$status=sanitize_key($r->get_param('status')??'all');$search=sanitize_text_field($r->get_param('search')??'');$c=EzLens_Auth_Campaign::get_instance();return ['data'=>$c->get_campaigns($status,$search,$limit,($page-1)*$limit),'total'=>$c->count_campaigns($status,$search),'page'=>$page,'per_page'=>$limit];}
    public function manager_tickets($r){$status=sanitize_key($r->get_param('status')??'all');return ['data'=>EzLens_Auth_Support::get_instance()->get_tickets($status,'',50,0)];}
    public function health(){return EzLens_Auth_Health::check();}
}
